" vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'majutsushi/tagbar'
Plugin 'kien/ctrlp.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdcommenter'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/syntastic'
Plugin 'klen/python-mode'
Plugin 'fatih/vim-go'
Plugin 'mileszs/ack.vim'
call vundle#end()
filetype plugin indent on


" basic
syntax on "语法支持
set laststatus=2 "始终显示状态栏
set tabstop=4 "一个制表符的长度
set softtabstop=4 "一个制表符的长度（可以大于tabstop）
set shiftwidth=4 "一个缩进的长度
set expandtab "使用空格替代制表符
set smarttab "智能制表符
set autoindent "自动缩进
set smartindent "只能缩进
set number "显示行号
set ruler "显示位置指示器
set backupdir=/tmp "设置备份文件目录
set directory=/tmp "设置临时文件目录
set ignorecase "检索时忽略大小写
set hls "检索时高亮显示匹配项
set helplang=cn "帮助系统设置为中文
set foldmethod=indent "代码折叠
set foldlevel=99
set backspace=2

colorscheme molokai
set guifont=Monaco:h14

set completeopt=menu


" bind Ctrl+<movement> keys to move around the windows, instead of using Ctrl+w + <movement>
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h


" easier moving of code blocks
" Try to go into visual mode (v), then select several lines of code here and
" then press ``>`` several times.
vnoremap < <gv
vnoremap > >gv


" nerdtree
nmap <F6> :NERDTreeToggle<cr>
let NERDTreeIgnore = ['\.pyc$', '__pycache__']


" tagbar
nmap <F8> :TagbarToggle<CR>
let g:tagbar_autofocus = 1


" vim-airline
nnoremap <C-n> :bp<CR>
nnoremap <C-m> :bn<CR>
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1


" syntastic
let g:syntastic_ignore_files = ['\.py$']


" ack
let g:ackprg = 'ag --nogroup --nocolor --column'


" yapf
autocmd FileType python nnoremap <leader>y :0,$!yapf<Cr><C-o>


" python-mode
let g:pymode_python = 'python3'
let g:pymode_lint_ignore="E501"
let g:pymode_folding = 1
let g:pymode_rope_completion = 0  "YCM is enough
let g:pymode_rope_goto_definition_cmd = 'e'
let g:pymode_lint_checkers = ['pyflakes', 'pep8', 'pylint']


" YCM
" let g:loaded_youcompleteme = 1


" vim-go
let mapleader = ","
au FileType go nmap <Leader>s <Plug>(go-implements)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
au FileType go nmap <Leader>e <Plug>(go-rename)
