" vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'majutsushi/tagbar'
Plugin 'kien/ctrlp.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdcommenter'
Plugin 'Valloric/YouCompleteMe'
Plugin 'python-mode/python-mode'
Plugin 'fatih/vim-go'
Plugin 'mileszs/ack.vim'
Plugin 'w0rp/ale'
Plugin 'avakhov/vim-yaml'
call vundle#end()
filetype plugin indent on


" for YCM and python-mode, ignore warn in python3.7
if has('python3')
  silent! python3 1
endif


" basic
let mapleader = ","
syntax on "语法支持
set laststatus=2 "始终显示状态栏
set smarttab "智能制表符
set autoindent "自动缩进
set smartindent "只能缩进
set number "显示行号
set ruler "显示位置指示器
set backupdir=/tmp "设置备份文件目录
set directory=/tmp "设置临时文件目录
set ignorecase "检索时忽略大小写
set hls "检索时高亮显示匹配项
set helplang=cn "帮助系统设置为中文
set foldmethod=indent "代码折叠
set foldlevel=99
set backspace=indent,eol,start

colorscheme molokai
set guifont=Monaco:h14
set completeopt=menu


" Set space indent for python files
autocmd Filetype python setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

" Set space indent for javescript files
autocmd Filetype javascript setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2



" bind Ctrl+<movement> keys to move around the windows, instead of using Ctrl+w + <movement>
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l
nnoremap <c-h> <c-w>h


" easier moving of code blocks
vnoremap < <gv
vnoremap > >gv


" nerdtree
nnoremap <F6> :NERDTreeToggle<CR>
let NERDTreeIgnore = ['\.pyc$', '__pycache__']


" tagbar
nnoremap <F8> :TagbarToggle<CR>
let g:tagbar_autofocus = 1


" vim-airline
nnoremap <C-c>n :bp<CR>
nnoremap <C-c>m :bn<CR>
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1


" ack
let g:ackprg = 'ag --nogroup --nocolor --column'


" python-mode
" python-mode prefix use <C-c>
nnoremap <C-c> <silent> <C-c>
let g:pymode_python = 'python3'
let g:pymode_lint_ignore="E501,F0002,C0111,E402"
let g:pymode_rope = 1
let g:pymode_rope_completion = 0  "YCM is enough
let g:pymode_rope_goto_definition_cmd = 'e'
let g:pymode_lint = 0   " Ale is enough


" ale
"let g:ale_linters_explicit = 1 " TODO: bug, new buffer will not load linters
let b:ale_linters = {'javascript': ['eslint'], 'python': ['pyflakes', 'flake8']}
let g:ale_fixers = {'javascript': ['eslint'], 'python': ['yapf']}
nmap <leader>y <Plug>(ale_fix)


" vim-go
au FileType go nmap <Leader>s <Plug>(go-implements)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
au FileType go nmap <Leader>e <Plug>(go-rename)
